eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761

spring:
  cloud:
    config:
      import: optional:configserver:http://localhost:8888

